/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as SubscribeSuccessRouteImport } from './routes/subscribe-success'
import { Route as SubmitProjectRouteImport } from './routes/submit-project'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MyRequestsRouteImport } from './routes/my-requests'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VipIndexRouteImport } from './routes/vip.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AdsAdIdRouteImport } from './routes/ads.$adId'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedAdminVipRouteImport } from './routes/_authenticated/admin.vip'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin.submissions'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminPendingProjectsRouteImport } from './routes/_authenticated/admin.pending-projects'
import { Route as AuthenticatedAdminMyProjectsRouteImport } from './routes/_authenticated/admin.my-projects'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin.employees'
import { Route as AuthenticatedAdminChatRouteImport } from './routes/_authenticated/admin.chat'
import { Route as AuthenticatedAdminBotTrainingRouteImport } from './routes/_authenticated/admin.bot-training'
import { Route as AuthenticatedAdminBotTestRouteImport } from './routes/_authenticated/admin.bot-test'
import { Route as AuthenticatedAdminBotSettingsRouteImport } from './routes/_authenticated/admin.bot-settings'
import { Route as AuthenticatedAdminAdsRouteImport } from './routes/_authenticated/admin.ads'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeSuccessRoute = SubscribeSuccessRouteImport.update({
  id: '/subscribe-success',
  path: '/subscribe-success',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitProjectRoute = SubmitProjectRouteImport.update({
  id: '/submit-project',
  path: '/submit-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRequestsRoute = MyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VipIndexRoute = VipIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VipRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsAdIdRoute = AdsAdIdRouteImport.update({
  id: '/$adId',
  path: '/$adId',
  getParentRoute: () => AdsRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVipRoute = AuthenticatedAdminVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPendingProjectsRoute =
  AuthenticatedAdminPendingProjectsRouteImport.update({
    id: '/pending-projects',
    path: '/pending-projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMyProjectsRoute =
  AuthenticatedAdminMyProjectsRouteImport.update({
    id: '/my-projects',
    path: '/my-projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChatRoute = AuthenticatedAdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBotTrainingRoute =
  AuthenticatedAdminBotTrainingRouteImport.update({
    id: '/bot-training',
    path: '/bot-training',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBotTestRoute =
  AuthenticatedAdminBotTestRouteImport.update({
    id: '/bot-test',
    path: '/bot-test',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBotSettingsRoute =
  AuthenticatedAdminBotSettingsRouteImport.update({
    id: '/bot-settings',
    path: '/bot-settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdsRoute = AuthenticatedAdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-requests': typeof MyRequestsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/submit-project': typeof SubmitProjectRoute
  '/subscribe-success': typeof SubscribeSuccessRoute
  '/thank-you': typeof ThankYouRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vip': typeof VipRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/ads/$adId': typeof AdsAdIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/project/$id': typeof ProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/vip/': typeof VipIndexRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/bot-settings': typeof AuthenticatedAdminBotSettingsRoute
  '/admin/bot-test': typeof AuthenticatedAdminBotTestRoute
  '/admin/bot-training': typeof AuthenticatedAdminBotTrainingRoute
  '/admin/chat': typeof AuthenticatedAdminChatRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/my-projects': typeof AuthenticatedAdminMyProjectsRoute
  '/admin/pending-projects': typeof AuthenticatedAdminPendingProjectsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vip': typeof AuthenticatedAdminVipRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-requests': typeof MyRequestsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/submit-project': typeof SubmitProjectRoute
  '/subscribe-success': typeof SubscribeSuccessRoute
  '/thank-you': typeof ThankYouRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/ads/$adId': typeof AdsAdIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/project/$id': typeof ProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/vip': typeof VipIndexRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/bot-settings': typeof AuthenticatedAdminBotSettingsRoute
  '/admin/bot-test': typeof AuthenticatedAdminBotTestRoute
  '/admin/bot-training': typeof AuthenticatedAdminBotTrainingRoute
  '/admin/chat': typeof AuthenticatedAdminChatRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/my-projects': typeof AuthenticatedAdminMyProjectsRoute
  '/admin/pending-projects': typeof AuthenticatedAdminPendingProjectsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vip': typeof AuthenticatedAdminVipRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ads': typeof AdsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-requests': typeof MyRequestsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/submit-project': typeof SubmitProjectRoute
  '/subscribe-success': typeof SubscribeSuccessRoute
  '/thank-you': typeof ThankYouRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vip': typeof VipRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/ads/$adId': typeof AdsAdIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/project/$id': typeof ProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/vip/': typeof VipIndexRoute
  '/_authenticated/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/_authenticated/admin/bot-settings': typeof AuthenticatedAdminBotSettingsRoute
  '/_authenticated/admin/bot-test': typeof AuthenticatedAdminBotTestRoute
  '/_authenticated/admin/bot-training': typeof AuthenticatedAdminBotTrainingRoute
  '/_authenticated/admin/chat': typeof AuthenticatedAdminChatRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/my-projects': typeof AuthenticatedAdminMyProjectsRoute
  '/_authenticated/admin/pending-projects': typeof AuthenticatedAdminPendingProjectsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/vip': typeof AuthenticatedAdminVipRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/auth'
    | '/contact'
    | '/maintenance'
    | '/my-requests'
    | '/projects'
    | '/reset-password'
    | '/submit-project'
    | '/subscribe-success'
    | '/thank-you'
    | '/unsubscribe'
    | '/vip'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/employees'
    | '/ads/$adId'
    | '/email/unsubscribe'
    | '/project/$id'
    | '/projects/$projectId'
    | '/vip/'
    | '/admin/ads'
    | '/admin/bot-settings'
    | '/admin/bot-test'
    | '/admin/bot-training'
    | '/admin/chat'
    | '/admin/employees'
    | '/admin/messages'
    | '/admin/my-projects'
    | '/admin/pending-projects'
    | '/admin/projects'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/support'
    | '/admin/users'
    | '/admin/vip'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/auth'
    | '/contact'
    | '/maintenance'
    | '/my-requests'
    | '/projects'
    | '/reset-password'
    | '/submit-project'
    | '/subscribe-success'
    | '/thank-you'
    | '/unsubscribe'
    | '/chat'
    | '/dashboard'
    | '/employees'
    | '/ads/$adId'
    | '/email/unsubscribe'
    | '/project/$id'
    | '/projects/$projectId'
    | '/vip'
    | '/admin/ads'
    | '/admin/bot-settings'
    | '/admin/bot-test'
    | '/admin/bot-training'
    | '/admin/chat'
    | '/admin/employees'
    | '/admin/messages'
    | '/admin/my-projects'
    | '/admin/pending-projects'
    | '/admin/projects'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/support'
    | '/admin/users'
    | '/admin/vip'
    | '/lovable/email/suppression'
    | '/admin'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ads'
    | '/auth'
    | '/contact'
    | '/maintenance'
    | '/my-requests'
    | '/projects'
    | '/reset-password'
    | '/submit-project'
    | '/subscribe-success'
    | '/thank-you'
    | '/unsubscribe'
    | '/vip'
    | '/_authenticated/admin'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/ads/$adId'
    | '/email/unsubscribe'
    | '/project/$id'
    | '/projects/$projectId'
    | '/vip/'
    | '/_authenticated/admin/ads'
    | '/_authenticated/admin/bot-settings'
    | '/_authenticated/admin/bot-test'
    | '/_authenticated/admin/bot-training'
    | '/_authenticated/admin/chat'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/my-projects'
    | '/_authenticated/admin/pending-projects'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vip'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdsRoute: typeof AdsRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MyRequestsRoute: typeof MyRequestsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SubmitProjectRoute: typeof SubmitProjectRoute
  SubscribeSuccessRoute: typeof SubscribeSuccessRoute
  ThankYouRoute: typeof ThankYouRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VipRoute: typeof VipRouteWithChildren
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ProjectIdRoute: typeof ProjectIdRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe-success': {
      id: '/subscribe-success'
      path: '/subscribe-success'
      fullPath: '/subscribe-success'
      preLoaderRoute: typeof SubscribeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-project': {
      id: '/submit-project'
      path: '/submit-project'
      fullPath: '/submit-project'
      preLoaderRoute: typeof SubmitProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip/': {
      id: '/vip/'
      path: '/'
      fullPath: '/vip/'
      preLoaderRoute: typeof VipIndexRouteImport
      parentRoute: typeof VipRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/$adId': {
      id: '/ads/$adId'
      path: '/$adId'
      fullPath: '/ads/$adId'
      preLoaderRoute: typeof AdsAdIdRouteImport
      parentRoute: typeof AdsRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/vip': {
      id: '/_authenticated/admin/vip'
      path: '/vip'
      fullPath: '/admin/vip'
      preLoaderRoute: typeof AuthenticatedAdminVipRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pending-projects': {
      id: '/_authenticated/admin/pending-projects'
      path: '/pending-projects'
      fullPath: '/admin/pending-projects'
      preLoaderRoute: typeof AuthenticatedAdminPendingProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/my-projects': {
      id: '/_authenticated/admin/my-projects'
      path: '/my-projects'
      fullPath: '/admin/my-projects'
      preLoaderRoute: typeof AuthenticatedAdminMyProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chat': {
      id: '/_authenticated/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AuthenticatedAdminChatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bot-training': {
      id: '/_authenticated/admin/bot-training'
      path: '/bot-training'
      fullPath: '/admin/bot-training'
      preLoaderRoute: typeof AuthenticatedAdminBotTrainingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bot-test': {
      id: '/_authenticated/admin/bot-test'
      path: '/bot-test'
      fullPath: '/admin/bot-test'
      preLoaderRoute: typeof AuthenticatedAdminBotTestRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bot-settings': {
      id: '/_authenticated/admin/bot-settings'
      path: '/bot-settings'
      fullPath: '/admin/bot-settings'
      preLoaderRoute: typeof AuthenticatedAdminBotSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ads': {
      id: '/_authenticated/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdsRoute: typeof AuthenticatedAdminAdsRoute
  AuthenticatedAdminBotSettingsRoute: typeof AuthenticatedAdminBotSettingsRoute
  AuthenticatedAdminBotTestRoute: typeof AuthenticatedAdminBotTestRoute
  AuthenticatedAdminBotTrainingRoute: typeof AuthenticatedAdminBotTrainingRoute
  AuthenticatedAdminChatRoute: typeof AuthenticatedAdminChatRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminMyProjectsRoute: typeof AuthenticatedAdminMyProjectsRoute
  AuthenticatedAdminPendingProjectsRoute: typeof AuthenticatedAdminPendingProjectsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVipRoute: typeof AuthenticatedAdminVipRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdsRoute: AuthenticatedAdminAdsRoute,
  AuthenticatedAdminBotSettingsRoute: AuthenticatedAdminBotSettingsRoute,
  AuthenticatedAdminBotTestRoute: AuthenticatedAdminBotTestRoute,
  AuthenticatedAdminBotTrainingRoute: AuthenticatedAdminBotTrainingRoute,
  AuthenticatedAdminChatRoute: AuthenticatedAdminChatRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminMyProjectsRoute: AuthenticatedAdminMyProjectsRoute,
  AuthenticatedAdminPendingProjectsRoute:
    AuthenticatedAdminPendingProjectsRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVipRoute: AuthenticatedAdminVipRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdsRouteChildren {
  AdsAdIdRoute: typeof AdsAdIdRoute
}

const AdsRouteChildren: AdsRouteChildren = {
  AdsAdIdRoute: AdsAdIdRoute,
}

const AdsRouteWithChildren = AdsRoute._addFileChildren(AdsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface VipRouteChildren {
  VipIndexRoute: typeof VipIndexRoute
}

const VipRouteChildren: VipRouteChildren = {
  VipIndexRoute: VipIndexRoute,
}

const VipRouteWithChildren = VipRoute._addFileChildren(VipRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdsRoute: AdsRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  MaintenanceRoute: MaintenanceRoute,
  MyRequestsRoute: MyRequestsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SubmitProjectRoute: SubmitProjectRoute,
  SubscribeSuccessRoute: SubscribeSuccessRoute,
  ThankYouRoute: ThankYouRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VipRoute: VipRouteWithChildren,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ProjectIdRoute: ProjectIdRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
