// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { normalizeSupabaseUrl } from '@/lib/supabase-url';

function readProcessEnv(name: string) {
  return typeof process !== 'undefined' ? process.env?.[name] : undefined;
}

function normalizeSupabaseKey(rawKey: string | null | undefined) {
  return rawKey
    ?.trim()
    .replace(/^['"]|['"]$/g, '')
    .replace(/^Bearer\s+/i, '')
    .replace(/\s+/g, '') || '';
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    normalizeSupabaseUrl(
      import.meta.env.NEXT_PUBLIC_SUPABASE_URL ||
      import.meta.env.VITE_SUPABASE_URL ||
      readProcessEnv('NEXT_PUBLIC_SUPABASE_URL') ||
      readProcessEnv('SUPABASE_URL')
    );
  const SUPABASE_PUBLISHABLE_KEY =
    normalizeSupabaseKey(
      import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
      import.meta.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
      import.meta.env.VITE_SUPABASE_ANON_KEY ||
      import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      readProcessEnv('NEXT_PUBLIC_SUPABASE_ANON_KEY') ||
      readProcessEnv('NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY') ||
      readProcessEnv('SUPABASE_ANON_KEY') ||
      readProcessEnv('SUPABASE_PUBLISHABLE_KEY')
    );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing database environment variable(s): ${missing.join(', ')}. Add them in Vercel Environment Variables.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

